In [8]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from keras.models import Sequential
from keras.layers import Dense, Dropout
from keras.wrappers.scikit_learn import KerasRegressor

In [10]:
# load dataset
df = pd.read_csv("housing.tsv", delim_whitespace=True, header=None)
dataset = dataframe.values
# split into input (X) and output (Y) variables
X = dataset[:,0:13]
Y = dataset[:,13]

In [10]:
# load dataset
df = pd.read_csv("housing.tsv", delim_whitespace=True, header=None)
dataset = dataframe.values
# split into input (X) and output (Y) variables
X = dataset[:,0:13]
Y = dataset[:,13]

In [11]:
train_x, test_x, train_y, test_y = train_test_split(X, Y, test_size=0.30)

In [12]:
model = Sequential()
model.add(Dense(15, input_dim=13, kernel_initializer='normal', activation='relu'))
model.add(Dropout(0.15))
model.add(Dense(15, input_dim=15, kernel_initializer='normal', activation='relu'))
model.add(Dense(1, kernel_initializer='normal'))
# Compile model
model.compile(loss='mean_squared_error', optimizer='adam')

In [16]:
history = model.fit(train_x, train_y, validation_data=(test_x, test_y), verbose=0, batch_size=3, epochs=300)

In [18]:
model.predict(test_x)

array([[14.132506 ],
       [16.324308 ],
       [15.527198 ],
       [39.63414  ],
       [13.658042 ],
       [14.633054 ],
       [18.765368 ],
       [11.864763 ],
       [16.507845 ],
       [19.17887  ],
       [18.960487 ],
       [18.82261  ],
       [17.793629 ],
       [16.489353 ],
       [15.697791 ],
       [14.355033 ],
       [14.682246 ],
       [17.493176 ],
       [19.190975 ],
       [20.619196 ],
       [13.085225 ],
       [26.212515 ],
       [17.583515 ],
       [25.224184 ],
       [17.606062 ],
       [11.7769375],
       [11.0244055],
       [22.452375 ],
       [12.984436 ],
       [35.263103 ],
       [11.906454 ],
       [14.274056 ],
       [16.094267 ],
       [25.211935 ],
       [30.40316  ],
       [18.922716 ],
       [33.163784 ],
       [33.243706 ],
       [14.001108 ],
       [14.87784  ],
       [10.642231 ],
       [10.510643 ],
       [36.348274 ],
       [15.45944  ],
       [44.218033 ],
       [18.935871 ],
       [30.907442 ],
       [27.88

In [20]:
dir(model)
#.predict_probability(text_x)

['_TF_MODULE_IGNORED_PROPERTIES',
 '__call__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_activity_regularizer',
 '_add_trackable',
 '_add_variable_with_custom_getter',
 '_assert_compile_was_called',
 '_assert_weights_created',
 '_auto_track_sub_layers',
 '_autocast',
 '_autographed_call',
 '_base_model_initialized',
 '_build_graph_network_for_inferred_shape',
 '_build_input_shape',
 '_call_accepts_kwargs',
 '_call_arg_was_passed',
 '_call_fn_arg_defaults',
 '_call_fn_arg_positions',
 '_call_fn_args',
 '_call_full_argspec',
 '_callable_losses',
 '_cast_single_input',
 '_check_call_args',
 '_checkpoint_dependencies',
 '_clear_los

In [21]:
model.predict_proba

[<tf.Variable 'dense_1/kernel:0' shape=(13, 15) dtype=float32, numpy=
 array([[-1.15427867e-01,  4.67266962e-02, -4.40924391e-02,
         -6.88875914e-02, -5.19863479e-02, -2.98533738e-01,
         -5.06004632e-01, -4.50012147e-01,  1.06983924e+00,
         -6.86887860e-01, -6.84824586e-02, -3.93952243e-03,
          8.08721688e-03, -9.31126952e-01, -9.54064280e-02],
        [-1.42320590e-02, -4.48135007e-03, -2.10056063e-02,
          2.27736980e-01, -7.32340068e-02,  1.49313927e-01,
          1.40425995e-01, -4.03886810e-02,  5.06427512e-02,
         -5.97738661e-02,  4.25935276e-02,  1.25532513e-02,
          1.74133014e-02,  4.66452688e-02,  1.07903443e-01],
        [ 5.60892001e-02,  5.31800464e-02,  1.31238863e-01,
         -1.10374540e-02, -7.79943392e-02,  1.00267075e-01,
          2.35318616e-01, -3.04703504e-01, -1.54261291e+00,
         -2.63101459e-01, -6.69854507e-03, -2.04100390e-03,
         -3.70096326e-01, -2.20289696e-02, -2.56656736e-01],
        [ 4.27034944e-02,  

In [23]:
model.predict_proba(test_x)

Instructions for updating:
Please use `model.predict()` instead.


array([[14.132506 ],
       [16.324308 ],
       [15.527198 ],
       [39.63414  ],
       [13.658042 ],
       [14.633054 ],
       [18.765368 ],
       [11.864763 ],
       [16.507845 ],
       [19.17887  ],
       [18.960487 ],
       [18.82261  ],
       [17.793629 ],
       [16.489353 ],
       [15.697791 ],
       [14.355033 ],
       [14.682246 ],
       [17.493176 ],
       [19.190975 ],
       [20.619196 ],
       [13.085225 ],
       [26.212515 ],
       [17.583515 ],
       [25.224184 ],
       [17.606062 ],
       [11.7769375],
       [11.0244055],
       [22.452375 ],
       [12.984436 ],
       [35.263103 ],
       [11.906454 ],
       [14.274056 ],
       [16.094267 ],
       [25.211935 ],
       [30.40316  ],
       [18.922716 ],
       [33.163784 ],
       [33.243706 ],
       [14.001108 ],
       [14.87784  ],
       [10.642231 ],
       [10.510643 ],
       [36.348274 ],
       [15.45944  ],
       [44.218033 ],
       [18.935871 ],
       [30.907442 ],
       [27.88